// Shared shape for the structured report data — replaces the old freeform
// markdown blob. Both properties.report_draft_markdown (pre-publish) and
// shared_reports.report_markdown (published) now store JSON.stringify() of
// this shape under those same (historically-named) text columns, rather
// than renaming columns for a schema that's still likely to evolve.
//
// Used by: app/api/report-draft/route.js (generation), app/manage/[id]/review
// (editing), app/report/[token] (customer-facing render).

export const RISK_LEVELS = ['Low', 'Moderate', 'High', 'Very High']
export const ACTION_PRIORITIES = ['High', 'Medium', 'Low']

export function emptyFinding() {
  return { category: '', finding: '', status: 'Needs Verification', recommendation: '', rationale: '' }
}

export function emptyActionItem() {
  return { action: '', zone: '', priority: 'Medium' }
}

export function blankReportData() {
  return {
    overallRiskRating: 'Moderate',
    summaryNarrative: '',
    topPriorities: ['', '', ''],
    wphBase: '',
    wphPlus: '',
    siteOverview: '',
    zones: [],
    actionPlan: [],
    photoCaptions: {},
    vegetationIntro: '',
    vegetationConsiderations: [],
    mitigationMeasurements: [],
  }
}

export function emptyVegetationConsideration() {
  return { zone: '', photoUrl: '', plantId: '', assessment: '', spacingGuidance: '' }
}

export function emptyMitigationMeasurement() {
  return { zone: '', label: '', category: '', unit: 'ft', photoUrl: '', estimatedValue: null, confidence: 'Unable to estimate', notes: '' }
}

// Per-photo caption, keyed by the entry's id — generated by the AI as
// action-oriented guidance ("Remove shrubs within 5 ft of the house...")
// rather than the inspector's raw field note. Falls back to the raw note
// for entries/photos predating this feature, so nothing goes blank.
export function getPhotoCaption(reportData, entry) {
  return reportData?.photoCaptions?.[entry.id] || entry.ai_caption || entry.note || ''
}

function zoneMatchKey(s) { return (s || '').toLowerCase().replace(/[^a-z0-9]/g, '') }

// Unified, orderable photo list for one zone — merges photos that came from
// field entries (via the `entries` table, matched by zone name) with photos
// added directly in the report editor (stored on the zone object itself as
// `extraPhotos`, since they aren't tied to any entry). Entries listed in
// reportData.excludedEntryIds are left out entirely (a reversible "remove
// from report" — the underlying entry/photo is untouched). Order follows
// zone.photoOrder (an array of item ids) when present, falling back to
// entries-then-extras; anything not yet present in a saved order (e.g. a
// photo added after the order was last saved) is appended at the end.
const DEFAULT_ADJUSTMENT = { zoom: 1, x: 0, y: 0 }

export function zonePhotoItems(zone, entries, reportData) {
  const zKey = zoneMatchKey(zone?.zone ?? zone)
  const excluded = new Set(reportData?.excludedEntryIds || [])
  const adjustments = reportData?.photoAdjustments || {}
  const entryPhotos = (entries || [])
    .filter(e => e.photo_url && zoneMatchKey(e.zone) === zKey && !excluded.has(e.id))
    .map(e => ({ id: `entry:${e.id}`, kind: 'entry', url: e.photo_url, caption: getPhotoCaption(reportData, e), status: e.status, entryId: e.id }))
  const extraPhotos = (zone?.extraPhotos || [])
    .map(p => ({ id: `extra:${p.id}`, kind: 'extra', url: p.url, caption: p.caption || '', status: p.status || null, extraId: p.id }))
  const all = [...entryPhotos, ...extraPhotos].map(p => ({ ...p, adjustment: adjustments[p.id] || DEFAULT_ADJUSTMENT }))
  const order = zone?.photoOrder
  if (order?.length) {
    const byId = new Map(all.map(p => [p.id, p]))
    const ordered = order.map(pid => byId.get(pid)).filter(Boolean)
    all.forEach(p => { if (!order.includes(p.id)) ordered.push(p) })
    return ordered
  }
  return all
}

// CSS transform for a photo's zoom/pan adjustment — shared by the read-only
// carousel and the review editor's tiles so "what you see while editing" is
// exactly what ends up on the report.
export function photoTransformStyle(adjustment) {
  const a = adjustment || DEFAULT_ADJUSTMENT
  return { transform: `scale(${a.zoom}) translate(${a.x}%, ${a.y}%)`, transformOrigin: 'center center' }
}

// Photos previously logged for this zone but currently excluded from the
// report — surfaced in the review editor so a removed photo can be
// restored.
export function excludedZonePhotos(zone, entries, reportData) {
  const zKey = zoneMatchKey(zone?.zone ?? zone)
  const excluded = new Set(reportData?.excludedEntryIds || [])
  return (entries || [])
    .filter(e => e.photo_url && zoneMatchKey(e.zone) === zKey && excluded.has(e.id))
    .map(e => ({ id: `entry:${e.id}`, kind: 'entry', url: e.photo_url, caption: getPhotoCaption(reportData, e), entryId: e.id }))
}

// Attempts to parse stored report text as the structured JSON shape.
// Returns null if it's not valid JSON — the caller treats that as a legacy
// plain-markdown report (from before this format existed) and falls back
// to rendering/editing it as raw text instead of crashing.
export function parseReportData(raw) {
  if (!raw) return null
  if (typeof raw === 'object') return raw
  try {
    const parsed = JSON.parse(raw)
    if (parsed && typeof parsed === 'object' && Array.isArray(parsed.zones)) return parsed
    return null
  } catch {
    return null
  }
}

// --- Section keys used by the review page's per-section edit/history UI ---
// 'exec' | 'overview' | 'action' | `zone:${zoneName}` — the same string is
// stored on report_versions.section so a version can be traced back to the
// part of the report it came from.

export const SECTION_LABELS = { exec: 'Executive Summary', overview: 'Site & Environmental Overview', action: 'Prioritized Action Plan', vegetation: 'Vegetation Considerations', measurements: 'Mitigation Measurements' }

export function sectionLabel(sectionKey) {
  if (!sectionKey) return 'Full Report'
  if (sectionKey.startsWith('zone:')) return sectionKey.slice(5)
  return SECTION_LABELS[sectionKey] || sectionKey
}

export function zoneSectionKey(zoneName) { return `zone:${zoneName}` }

// Pulls out just the fields relevant to one section from a full report data
// object, so version-history diffs only show what actually changed for that
// section rather than the whole report.
export function reportSectionSlice(reportData, sectionKey) {
  if (!reportData || !sectionKey) return reportData
  if (sectionKey === 'exec') {
    return {
      overallRiskRating: reportData.overallRiskRating,
      summaryNarrative: reportData.summaryNarrative,
      topPriorities: reportData.topPriorities,
      wphBase: reportData.wphBase,
      wphPlus: reportData.wphPlus,
    }
  }
  if (sectionKey === 'overview') return { siteOverview: reportData.siteOverview }
  if (sectionKey === 'action') return { actionPlan: reportData.actionPlan }
  if (sectionKey === 'vegetation') return { vegetationIntro: reportData.vegetationIntro, vegetationConsiderations: reportData.vegetationConsiderations }
  if (sectionKey === 'measurements') return { mitigationMeasurements: reportData.mitigationMeasurements }
  if (sectionKey.startsWith('zone:')) {
    const zoneName = sectionKey.slice(5)
    return (reportData.zones || []).find(z => z.zone === zoneName) ?? null
  }
  return reportData
}

// Friendly labels for the fields diffed in the history popup — falls back
// to the raw key (title-cased) for anything not listed.
const FIELD_LABELS = {
  overallRiskRating: 'Risk Rating', summaryNarrative: 'Summary', topPriorities: 'Top Priorities',
  wphBase: 'WPH Base', wphPlus: 'WPH Plus', siteOverview: 'Site Overview', actionPlan: 'Action Plan',
  zone: 'Zone Name', findings: 'Findings',
  vegetationIntro: 'Vegetation Intro', vegetationConsiderations: 'Vegetation Considerations',
  mitigationMeasurements: 'Mitigation Measurements',
}
function fieldLabel(key) { return FIELD_LABELS[key] || key.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase()) }

// Shallow field-by-field diff between two section slices (JSON-stringify
// comparison per top-level key, since findings/topPriorities are arrays of
// objects/strings where a plain string diff is still useful to a human even
// without a nested field-level diff). Returns a list of { field, before,
// after } for keys that differ.
export function diffSectionSlices(before, after) {
  if (!after) return []
  const keys = new Set([...Object.keys(before || {}), ...Object.keys(after || {})])
  const changes = []
  keys.forEach(key => {
    const b = before ? before[key] : undefined
    const a = after[key]
    const bStr = JSON.stringify(b ?? null)
    const aStr = JSON.stringify(a ?? null)
    if (bStr !== aStr) changes.push({ field: fieldLabel(key), before: b, after: a })
  })
  return changes
}

// Splits on whitespace, keeping trailing whitespace attached to each token
// so rejoining tokens reproduces the original spacing exactly.
function tokenizeForDiff(str) { return (str || '').match(/\S+\s*|\s+/g) || [] }

// Word-level diff (LCS-based) between two already-stringified values — used
// by the version-history UI so a one-word edit renders as a single flowing
// paragraph with just that word struck through/highlighted, instead of two
// full separate before/after blocks. Returns a list of
// { text, type: 'same' | 'removed' | 'added' } tokens in reading order:
// render 'removed' tokens struck through, 'added' tokens highlighted, 'same'
// tokens plain.
//
// The LCS table is O(n*m) in token count — fine for report-length text, but
// capped for anything huge (a giant JSON blob slipping through, say) so a
// pathological diff can't hang the tab; falls back to marking the whole
// thing removed+added (still correct, just not word-granular) past the cap.
const WORD_DIFF_TOKEN_CAP = 600
export function wordDiff(beforeStr, afterStr) {
  const a = tokenizeForDiff(beforeStr)
  const b = tokenizeForDiff(afterStr)
  if (a.length > WORD_DIFF_TOKEN_CAP || b.length > WORD_DIFF_TOKEN_CAP) {
    return [...a.map(text => ({ text, type: 'removed' })), ...b.map(text => ({ text, type: 'added' }))]
  }
  const n = a.length, m = b.length
  const dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0))
  for (let i = n - 1; i >= 0; i--) {
    for (let j = m - 1; j >= 0; j--) {
      dp[i][j] = a[i] === b[j] ? dp[i + 1][j + 1] + 1 : Math.max(dp[i + 1][j], dp[i][j + 1])
    }
  }
  const tokens = []
  let i = 0, j = 0
  while (i < n && j < m) {
    if (a[i] === b[j]) { tokens.push({ text: a[i], type: 'same' }); i++; j++ }
    else if (dp[i + 1][j] >= dp[i][j + 1]) { tokens.push({ text: a[i], type: 'removed' }); i++ }
    else { tokens.push({ text: b[j], type: 'added' }); j++ }
  }
  while (i < n) { tokens.push({ text: a[i], type: 'removed' }); i++ }
  while (j < m) { tokens.push({ text: b[j], type: 'added' }); j++ }
  return tokens
}
