// Shared shape for the structured report data — replaces the old freeform
// markdown blob. Both properties.report_draft_markdown (pre-publish) and
// shared_reports.report_markdown (published) now store JSON.stringify() of
// this shape under those same (historically-named) text columns, rather
// than renaming columns for a schema that's still likely to evolve.
//
// Used by: app/api/report-draft/route.js (generation), app/manage/[id]/review
// (editing), app/report/[token] (customer-facing render).

export const RISK_LEVELS = ['Low', 'Moderate', 'High', 'Very High']
export const ACTION_PRIORITIES = ['High', 'Medium', 'Low']

export function emptyFinding() {
  return { category: '', finding: '', status: 'Needs Verification', recommendation: '', rationale: '' }
}

export function emptyActionItem() {
  return { action: '', zone: '', priority: 'Medium' }
}

export function blankReportData() {
  return {
    overallRiskRating: 'Moderate',
    summaryNarrative: '',
    topPriorities: ['', '', ''],
    wphBase: '',
    wphPlus: '',
    siteOverview: '',
    zones: [],
    actionPlan: [],
    photoCaptions: {},
  }
}

// Per-photo caption, keyed by the entry's id — generated by the AI as
// action-oriented guidance ("Remove shrubs within 5 ft of the house...")
// rather than the inspector's raw field note. Falls back to the raw note
// for entries/photos predating this feature, so nothing goes blank.
export function getPhotoCaption(reportData, entry) {
  return reportData?.photoCaptions?.[entry.id] || entry.ai_caption || entry.note || ''
}

// Attempts to parse stored report text as the structured JSON shape.
// Returns null if it's not valid JSON — the caller treats that as a legacy
// plain-markdown report (from before this format existed) and falls back
// to rendering/editing it as raw text instead of crashing.
export function parseReportData(raw) {
  if (!raw) return null
  if (typeof raw === 'object') return raw
  try {
    const parsed = JSON.parse(raw)
    if (parsed && typeof parsed === 'object' && Array.isArray(parsed.zones)) return parsed
    return null
  } catch {
    return null
  }
}
